### ISSUE TITLE
RX error

### ISSUE THREAD

**Issue by abdullahyildiz** [lowRISC/ariane-ethernet#3]
I'm trying to use [ariane-ethernet](https://github.com/lowRISC/ariane-ethernet/tree/6a5436bf110f83ebb13119dbd82650ccd8f947c9) within [OpenPiton](https://github.com/PrincetonUniversity/openpiton) project.

For this, I made the relevant changes in RTL code and constraints (I didn't modify the Linux kernel configuration as the lowrisc-eth driver is already included in the kernel).

When the system boots, Linux kernel successfully loads the lowrisc-eth driver and OS successfully obtains an IP address:

![Screen Shot 2021-03-23 at 18 08 30](https://user-images.githubusercontent.com/3716793/112169061-e8e3d280-8c02-11eb-98b9-8c8bf8e30f35.png)

![Screen Shot 2021-03-23 at 18 09 17](https://user-images.githubusercontent.com/3716793/112169254-1761ad80-8c03-11eb-8614-96ea5fe7be7f.png)

However, when I try to run ping command OS cannot receive the ARP response and hence cannot proceed by sending ICMP packets:

![ss_ping_wireshark](https://user-images.githubusercontent.com/3716793/112165727-0d8a7b00-8c00-11eb-823a-479ae4bfd45d.png)

What can cause this? Is it a software or hardware problem?

**Comment by jrrk** [comment]
I have seen something similar where the kernel tells the PHY to begin auto negotiation, and it does not understand the response from the other end. If you disable PHY access it should default to a safe state and carry on working (if that is the problem indeed).

**Comment by abdullahyildiz** [comment]
@jrrk,

> If you disable PHY access it should default to a safe state and carry on working (if that is the problem indeed).

The same driver works with CVA6 bitstream without any problem.

Also there is [no difference](https://github.com/pulp-platform/ariane-sdk/compare/v0.3.0...v0.3.0-op) related to PHY/MAC between kernel configurations.

How can I disable PHY access in kernel?

**Comment by abdullahyildiz** [comment]
I came across a situation where ping worked but later it again stopped working:

![Screen Shot 2021-03-24 at 10 56 01](https://user-images.githubusercontent.com/3716793/112274831-fd21e100-8c8f-11eb-9d04-fe4158188b1b.png)

**Comment by jrrk** [comment]
If it’s the same version of lowrisc-eth that I remember then the MDIO interface to the PHY may be disabled using ifdefs within the code of that driver. Of course your RTL is different so there could be some other subtle issue. I recommend connecting the internal logic analyser (ILA) feature of Vivado to diagnose the internal state of the transceiver. This can be done at source or from the debug menu.

**Comment by JLValdivieso** [comment]
Hi @abdullahyildiz, have you found the solution to the problem?, I have the same problem with the Cheshire platform, I have not modified the linux driver, and after obtaining the IP, I can send packets, but I cannot receive.

**Comment by abdullahyildiz** [comment]
Hi @JLValdivieso,

We have not found a solution, unfortunately. I can only suggest checking the timing issues (if any) in your design.
